version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth

  api:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - .:/app
    command: [ 'air' ]
    links:
      - postgres:db
    ports:
      - "8080:8080"
    restart: always
